"""empty message

Revision ID: 18f40eea26dd
Revises: 
Create Date: 2019-08-12 14:31:35.497846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f40eea26dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filtered_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('smartpixl_recordId', sa.Integer(), nullable=False),
    sa.Column('smartpixl_date', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=75), nullable=True),
    sa.Column('last_name', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_source', sa.String(length=25), nullable=True),
    sa.Column('email_status', sa.String(length=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filtered_data_companyId'), 'filtered_data', ['companyId'], unique=False)
    op.create_table('smart_pixl_cron',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_pixl_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('pixlId', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('pixlId')
    )
    op.create_index(op.f('ix_smart_pixl_params_companyId'), 'smart_pixl_params', ['companyId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_pixl_params_companyId'), table_name='smart_pixl_params')
    op.drop_table('smart_pixl_params')
    op.drop_table('smart_pixl_cron')
    op.drop_index(op.f('ix_filtered_data_companyId'), table_name='filtered_data')
    op.drop_table('filtered_data')
    # ### end Alembic commands ###
